import {describe,it,expect} from "vitest";
import {DEFAULT_PROVIDER_TRAY,trayLimits,trayPercent} from "./trayStudioModel";
import type {ProviderUsageSnapshot} from "../../types/bridge";
const sample={providerId:"codex",errorState:"ready",sourceLabel:"oauth",primaryLabel:"Session",primary:{usedPercent:21.25,remainingPercent:78.75,windowMinutes:300},secondary:{usedPercent:50,remainingPercent:50,windowMinutes:10080},secondaryLabel:"Weekly",extraRateWindows:[{id:"spark",title:"Spark",window:{usedPercent:0,remainingPercent:100,windowMinutes:300}}]} as ProviderUsageSnapshot;
describe("tray selection truth",()=>{
 it("uses exact reported windows, including extras",()=>{expect(trayLimits(sample).map(w=>w.id)).toEqual(["primary:Session:300","secondary:Weekly:10080","extra:spark:300"]);});
 it("preserves exact percent and never substitutes another limit",()=>{const c={...DEFAULT_PROVIDER_TRAY,limitId:"primary:Session:300"};expect(trayPercent(sample,c)).toBe(78.75);expect(trayPercent(sample,{...c,showAsUsed:true})).toBe(21.25);expect(trayPercent(sample,{...c,limitId:"retired"})).toBeNull();});
 it("fails closed for auth, absent snapshots and invalid numbers",()=>{const c={...DEFAULT_PROVIDER_TRAY,limitId:"primary:Session:300"};expect(trayPercent({...sample,errorState:"needsAuthentication"},c)).toBeNull();expect(trayPercent(undefined,c)).toBeNull();expect(trayPercent({...sample,primary:{...sample.primary,remainingPercent:NaN}},c)).toBeNull();});
 it("does not turn informational windows into quota meters",()=>{expect(trayLimits({...sample,primary:{...sample.primary,isInformational:true}}).some(w=>w.id.startsWith("primary:"))).toBe(false);});
});
import {TRAY_STYLE_OPTIONS,filterTrayProviders,trayAppearanceValueKey} from "./trayStudioModel";
import type {ProviderCatalogEntry,ProviderTrayConfig} from "../../types/bridge";
describe("tray studio model",()=>{
 it("mirrors the native healthy check for unavailable and disabled sources",()=>{const c={...DEFAULT_PROVIDER_TRAY,limitId:"primary:Session:300"};expect(trayPercent({...sample,sourceLabel:"unavailable"},c)).toBeNull();expect(trayPercent({...sample,sourceLabel:"disabled"},c)).toBeNull();expect(trayPercent({...sample,error:"Timeout"},c)).toBeNull();});
 it("keeps 0% and 100% as real readings in both semantics",()=>{const c={...DEFAULT_PROVIDER_TRAY,limitId:"primary:Session:300"};const full={...sample,primary:{...sample.primary,usedPercent:100,remainingPercent:0}};expect(trayPercent(full,{...c,showAsUsed:true})).toBe(100);expect(trayPercent(full,c)).toBe(0);});
 it("offers exactly the native renderer's styles",()=>{expect(TRAY_STYLE_OPTIONS.map(([s])=>s)).toEqual(["ring","arc","bar","badge","orbit","mark"]);});
 it.each([1,6,12,24,70])("filters a registry of %i providers without a fixed count",(count)=>{const catalog=Array.from({length:count},(_,i)=>({id:`p${i}`,displayName:`Provider ${i}`})) as ProviderCatalogEntry[];expect(filterTrayProviders(catalog,"")).toHaveLength(count);expect(filterTrayProviders(catalog,`provider ${count-1}`).map(p=>p.id)).toContain(`p${count-1}`);expect(filterTrayProviders(catalog,"zzz")).toHaveLength(0);});
 it("summarizes the real tray treatment for the Appearance summary",()=>{const cfg=(color:ProviderTrayConfig["color"],enabled=true)=>({...DEFAULT_PROVIDER_TRAY,enabled,color});expect(trayAppearanceValueKey({trayIconMode:"single",providerTrayConfigs:{}})).toBe("AppearanceTraySingleIcon");expect(trayAppearanceValueKey({trayIconMode:"perProvider"})).toBe("AppearanceTrayProviderAccent");expect(trayAppearanceValueKey({trayIconMode:"single",providerTrayConfigs:{a:cfg("identity"),b:cfg("silver",false)}})).toBe("AppearanceTrayQuotalisPalette");expect(trayAppearanceValueKey({trayIconMode:"single",providerTrayConfigs:{a:cfg("identity"),b:cfg("silver")}})).toBe("AppearanceTrayMixed");});
});
