import {useOptionalLocale} from "../../hooks/useLocale";
import type {LocaleKey} from "../../i18n/keys";
const COPY: Record<string,LocaleKey> = {
  "Reset presentation changes formatting only; the reported reset instant stays unchanged.": "V2ResetExplanation",
  "Preset": "V2Editor1",
  "Modules shown": "V2Editor2",
  "Order": "V2Editor3",
  "Advanced formatting": "V2Editor4",
  "Timezone": "V2Editor5",
  "Follow System": "V2Editor6",
  "Custom": "V2Editor7",
  "Regional Format": "V2Editor8",
  "Follow UI Language": "V2Editor9",
  "Clock Format": "V2Editor10",
  "Meridiem": "V2Editor11",
  "Localized": "V2Editor12",
  "Month": "V2Editor13",
  "Numeric": "V2Editor14",
  "Short Name": "V2Editor15",
  "Full Name": "V2Editor16",
  "Weekday": "V2Editor17",
  "Short": "V2Editor18",
  "Countdown Detail": "V2Editor19",
  "Adaptive": "V2Editor20",
  "Compact": "V2Editor21",
  "Detailed": "V2Editor22",
  "English": "V2Editor23",
  "Reset Display": "V2Editor24",
  "How reset times are shown": "V2Editor25",
  "Apply to": "V2Editor26",
  "Global": "V2Editor27",
  "Customize by surface": "V2Editor28",
  "Saving…": "V2Editor29",
  "Countdown Only": "V2Editor30",
  "Date & Time": "V2Editor31",
  "Countdown + Date & Time": "V2Editor32",
  "Full": "V2Editor33",
  "Countdown": "V2Editor34",
  "Date": "V2Editor35",
  "Time": "V2Editor36",
  "Taskbar": "V2Editor37",
  "Top": "V2Editor38",
  "Edge": "V2Editor39",
  "HUD": "V2Editor40",
  "Quick Panel": "V2Editor41",
  "Dashboard": "V2Editor42",
  "Provider Display": "V2Editor43",
  "Tray": "V2Editor44",
  "Follow Global": "V2Editor45",
  "Edit": "V2Editor46",
  "Customize": "V2Editor47",
  "Done": "V2Editor48",
  "Reset to Global": "V2Editor49",
  "Surface identities": "V2Editor50",
  "Apply theme to": "V2Editor51",
  "Theme assignment": "V2Editor52",
  "Global default": "V2Editor53",
  "Current profile": "V2Editor54",
  "Use inherited theme": "V2Editor55",
  "Preview structure": "V2Editor56",
  "Theme preview structure": "V2Editor57",
  "Frame": "V2Editor58",
  "Meter": "V2Editor59",
  "Motion": "V2Editor60",
  "Selected": "V2Editor61",
  "Apply theme": "V2Editor62",
  "Effective source": "V2Editor63",
  "Change the complete visual identity—finish, rim, icon frame, typography and depth—without changing placement or quota data.": "V2Editor64",
  "Surface overrides profile; profile overrides global. Provider brand colors remain independent from the selected theme.": "V2Editor65",
  "Hover or focus a card to reveal details. This preview does not change your desktop structure.": "V2Editor66"
};
/** Localized copy for the existing reset/theme editors; identity names stay intact. */
export function useSettingsCopy() { const locale=useOptionalLocale(); return (text:string) => COPY[text] && locale ? locale.t(COPY[text]) : text; }
