/**
 * QuotaArc V9 — TypeScript contract for the Rust-authoritative surface
 * layout runtime (`quotalis_core::surface_layout`).
 *
 * This module deliberately contains NO geometry algorithm. Rust owns the
 * monitor work area, scale factor, physical/logical conversion, and native
 * windows, so Rust computes every production surface dimension. The
 * frontend consumes resolved DTOs (via Tauri commands/events or the
 * checked-in golden fixtures) for CSS/SVG layout only.
 *
 * Golden fixtures: `docs/golden_surface_layouts.json` is generated BY the
 * Rust authority (see `surface_layout::golden_tests`) and pinned there by a
 * byte-exact serialization test. This module only parses and validates it.
 */

export type SurfaceKindToken =
  | "taskbar"
  | "top"
  | "edge"
  | "hud"
  | "quick-panel"
  | "dashboard"
  | "settings";

export type SurfaceStateToken = "compact" | "hover" | "expanded";

/** Mirror of `quotalis_core::surface_layout::ResolvedSurfaceLayout` (camelCase). */
export interface ResolvedSurfaceLayoutDto {
  surface: SurfaceKindToken;
  state: SurfaceStateToken;
  windowBoundsLogical: [number, number];
  viewportBoundsLogical: [number, number];
  safeContentBounds: [number, number];
  center: [number, number];
  scale: number;
  scaleFactor: number;
  orbitRadius: number;
  instrumentSize: number;
  labelBounds: [number, number];
  clampedBy: string | null;
}

const SURFACE_TOKENS: readonly SurfaceKindToken[] = [
  "taskbar",
  "top",
  "edge",
  "hud",
  "quick-panel",
  "dashboard",
  "settings",
];

const STATE_TOKENS: readonly SurfaceStateToken[] = ["compact", "hover", "expanded"];

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function isFinitePair(value: unknown): value is [number, number] {
  return (
    Array.isArray(value) &&
    value.length === 2 &&
    isFiniteNumber(value[0]) &&
    isFiniteNumber(value[1])
  );
}

/**
 * Validate an untrusted payload (Tauri event/command JSON) as a resolved
 * layout DTO. Returns `null` for corrupt data so callers can fall back to
 * a known-good fixture deterministically.
 */
export function parseResolvedSurfaceLayout(
  payload: unknown,
): ResolvedSurfaceLayoutDto | null {
  if (typeof payload !== "object" || payload === null) return null;
  const dto = payload as Record<string, unknown>;
  if (!SURFACE_TOKENS.includes(dto.surface as SurfaceKindToken)) return null;
  if (!STATE_TOKENS.includes(dto.state as SurfaceStateToken)) return null;
  if (
    !isFinitePair(dto.windowBoundsLogical) ||
    !isFinitePair(dto.viewportBoundsLogical) ||
    !isFinitePair(dto.safeContentBounds) ||
    !isFinitePair(dto.center) ||
    !isFinitePair(dto.labelBounds)
  ) {
    return null;
  }
  if (!isFiniteNumber(dto.scale) || !isFiniteNumber(dto.scaleFactor)) return null;
  if (!isFiniteNumber(dto.orbitRadius) || !isFiniteNumber(dto.instrumentSize)) {
    return null;
  }
  const [w, h] = dto.windowBoundsLogical;
  if (w <= 0 || h <= 0) return null;
  const [vw, vh] = dto.viewportBoundsLogical;
  if (vw > w || vh > h) return null;
  if (
    dto.clampedBy !== null &&
    dto.clampedBy !== undefined &&
    typeof dto.clampedBy !== "string"
  ) {
    return null;
  }
  return {
    surface: dto.surface as SurfaceKindToken,
    state: dto.state as SurfaceStateToken,
    windowBoundsLogical: dto.windowBoundsLogical,
    viewportBoundsLogical: dto.viewportBoundsLogical,
    safeContentBounds: dto.safeContentBounds,
    center: dto.center,
    scale: dto.scale,
    scaleFactor: dto.scaleFactor,
    orbitRadius: dto.orbitRadius,
    instrumentSize: dto.instrumentSize,
    labelBounds: dto.labelBounds,
    clampedBy: dto.clampedBy ?? null,
  };
}

/**
 * CSS variables derived from a resolved DTO. Surface components consume
 * these instead of computing geometry; values are already logical px.
 */
export function layoutCssVariables(layout: ResolvedSurfaceLayoutDto): Record<string, string> {
  const [w, h] = layout.windowBoundsLogical;
  return {
    "--qa-surface-width": `${w}px`,
    "--qa-surface-height": `${h}px`,
    "--qa-surface-center-x": `${layout.center[0]}px`,
    "--qa-surface-center-y": `${layout.center[1]}px`,
    "--qa-surface-orbit-radius": `${layout.orbitRadius}px`,
    "--qa-surface-instrument-size": `${layout.instrumentSize}px`,
  };
}
