import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import {
  layoutCssVariables,
  parseResolvedSurfaceLayout,
  type ResolvedSurfaceLayoutDto,
} from "./surfaceSizing";

/**
 * Golden-fixture contract test: the fixtures are generated BY the Rust
 * authority (quotalis_core::surface_layout::golden_tests) and pinned there by a
 * byte-exact serialization test. This suite proves the TypeScript layer
 * consumes exactly what Rust produces — no second geometry algorithm.
 */
function loadGoldenFixtures(): Record<string, unknown> {
  // vitest runs with cwd = apps/desktop-tauri; repo docs live two levels up.
  const path = resolve(process.cwd(), "../../docs/golden_surface_layouts.json");
  return JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
}

const fixtures = loadGoldenFixtures();

const EXPECTED_KEYS = [
  "taskbar",
  "top",
  "edge",
  "hud",
  "quick-panel",
  "dashboard",
  "settings",
].flatMap((surface) =>
  ["compact", "hover", "expanded"].map((state) => `${surface}:${state}`),
);

describe("Rust golden-fixture contract", () => {
  it("contains all 7 surfaces × 3 states and nothing else", () => {
    expect(Object.keys(fixtures).sort()).toEqual([...EXPECTED_KEYS].sort());
  });

  it.each(EXPECTED_KEYS)("%s parses as a valid resolved layout DTO", (key) => {
    const dto = parseResolvedSurfaceLayout(fixtures[key]);
    expect(dto, `fixture ${key} must parse`).not.toBeNull();
  });

  it("every fixture obeys the V9 invariants", () => {
    const parsed: ResolvedSurfaceLayoutDto[] = EXPECTED_KEYS.map((key) => {
      const dto = parseResolvedSurfaceLayout(fixtures[key]);
      if (!dto) throw new Error(`fixture ${key} failed to parse`);
      return dto;
    });
    for (const dto of parsed) {
      const [w, h] = dto.windowBoundsLogical;
      const [vw, vh] = dto.viewportBoundsLogical;
      // Positive, finite, integer logical bounds.
      expect(w).toBeGreaterThan(0);
      expect(h).toBeGreaterThan(0);
      expect(Number.isInteger(w)).toBe(true);
      expect(Number.isInteger(h)).toBe(true);
      // Viewport never exceeds the window.
      expect(vw).toBeLessThanOrEqual(w);
      expect(vh).toBeLessThanOrEqual(h);
      // Center is inside the window.
      expect(dto.center[0]).toBeGreaterThanOrEqual(0);
      expect(dto.center[0]).toBeLessThanOrEqual(w);
      expect(dto.center[1]).toBeGreaterThanOrEqual(0);
      expect(dto.center[1]).toBeLessThanOrEqual(h);
      // Orbit stays inside the window.
      expect(dto.orbitRadius * 2).toBeLessThan(Math.max(w, h));
      // Instrument size is bounded.
      expect(dto.instrumentSize).toBeGreaterThanOrEqual(28);
      expect(dto.instrumentSize).toBeLessThanOrEqual(56);
    }
  });

  it("compact taskbar stays in the 360-440 × 90-140 envelope (Rust golden values)", () => {
    const dto = parseResolvedSurfaceLayout(fixtures["taskbar:compact"]);
    expect(dto?.windowBoundsLogical).toEqual([360, 140]);
    const expanded = parseResolvedSurfaceLayout(fixtures["taskbar:expanded"]);
    expect(expanded?.windowBoundsLogical[0]).toBe(640);
    expect(expanded?.windowBoundsLogical[1]).toBeLessThanOrEqual(340);
    expect(expanded?.clampedBy).toBe("work-area-height");
  });

  it("edge compact is thickness-first and clamps expanded width to the work area", () => {
    const compact = parseResolvedSurfaceLayout(fixtures["edge:compact"]);
    expect(compact?.windowBoundsLogical[0]).toBeLessThan(
      compact?.windowBoundsLogical[1] ?? Infinity,
    );
    const expanded = parseResolvedSurfaceLayout(fixtures["edge:expanded"]);
    expect(expanded?.windowBoundsLogical[0]).toBeLessThanOrEqual(260);
    expect(expanded?.windowBoundsLogical[1]).toBeLessThanOrEqual(520);
    expect(expanded?.clampedBy).toBe("work-area-width");
  });

  it("settings fits entirely within the reference work area", () => {
    const dto = parseResolvedSurfaceLayout(fixtures["settings:compact"]);
    expect(dto?.windowBoundsLogical[1]).toBeLessThanOrEqual(752);
    expect(dto?.clampedBy).toBe("work-area-fit");
  });
});

describe("resolved layout DTO validation", () => {
  it("rejects corrupt payloads instead of rendering them", () => {
    expect(parseResolvedSurfaceLayout(null)).toBeNull();
    expect(parseResolvedSurfaceLayout("garbage")).toBeNull();
    expect(
      parseResolvedSurfaceLayout({ surface: "unknown", state: "compact" }),
    ).toBeNull();
    expect(
      parseResolvedSurfaceLayout({
        surface: "taskbar",
        state: "compact",
        windowBoundsLogical: [Number.NaN, 100],
      }),
    ).toBeNull();
    expect(
      parseResolvedSurfaceLayout({
        surface: "taskbar",
        state: "compact",
        windowBoundsLogical: [-5, 100],
      }),
    ).toBeNull();
    expect(
      parseResolvedSurfaceLayout({
        surface: "taskbar",
        state: "compact",
        windowBoundsLogical: [400, 100],
        viewportBoundsLogical: [500, 100],
      }),
    ).toBeNull();
  });

  it("derives bounded CSS variables from a resolved DTO", () => {
    const dto = parseResolvedSurfaceLayout(fixtures["taskbar:compact"]);
    if (!dto) throw new Error("fixture failed to parse");
    const vars = layoutCssVariables(dto);
    expect(vars["--qa-surface-width"]).toBe("360px");
    expect(vars["--qa-surface-height"]).toBe("140px");
    expect(vars["--qa-surface-instrument-size"]).toBe("28px");
  });
});
